name: SSH Remote CI
on: push
jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Execute remote SSH command"
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          bash
          source ~/.bashrc
          cd /volume1/web/solidarity.nz/
          git stash
          git pull origin
          git checkout master
          bash build.sh